### ISSUE TITLE
Imprint link

### ISSUE THREAD

**Issue by tbba** [blaueQuelle/privacywire#1]
Hello, cool idea to start this new approach. Some comments:
- Since the banner could cover madatory footer links, it would be helpful if the banner would also show links to the imprint.
- Looks like the upcoming EU rules require us to give more information about things in "marketing", e.g. Matomo, Google etc.
- If you look at the "cookie selection" details, there is no way back to the intro banner, you have to make a decision there: So a "select all" button would serve the purpose better than a toggle button?

**Comment by webworkerJoshua** [comment]
Thanks for your feedback!
1) I agree, an "imprint" link makes sense. I [added](https://github.com/blaueQuelle/privacywire/releases/tag/0.0.4) the possibility for this. 
2) I also thought about that. Do you think of a solution like Cookiebot: 
<img width="717" alt="cookiebot" src="https://user-images.githubusercontent.com/44984072/75095954-74bba300-559a-11ea-84a9-47c57c34d1aa.png">
3) Maybe both - toggle & select all - would be good?  I could add that, too...

**Comment by tbba** [comment]
The imprint link is cool, thank you!! Yes, I was thinking of something like Borlabs or Cookiebot (I find Borlabs more elegant and less clunky.)

If I see the situation correctly, we do not yet have any confirmed legal regulations for the cookie banner in Germany. The BGH will decide on this in May. The conflicting conditions seem to be these:

1. a legal requirement to keep things simple for users, not difficult to read and not overloaded
2. an opt-in that must be fine-tuned, if the users want it, with justification, in groups and, if he digs deeper, then cookie by cookie.

None of this is clear yet. I have no idea if this nonsense with cookie forms is getting worse and worse or if this will be questioned by a wise court one day. Only a government agency could come up with that kind of crap. Apparently, government agencies love complicated forms.

At the moment, there's no threat of trouble in Germany, this blog rightly says,
https://marketingstratege.net/dsgvo-cookie-hinweis-beispiele/
but preparation can't hurt and in other European countries it might be worse already.

**Comment by tbba** [comment]
Can we close this (imprint is there) or do we leave it open for further comments?
