### ISSUE TITLE
Inlinescripts not working

### ISSUE THREAD

**Issue by vieregg-jfc** [blaueQuelle/privacywire#11]
Hey, I've noticed an error:

When I try to load an inline script it's not working (any more?). After putting the code in an external file, everything works likr a charm.

Even after upgrading from version 0.3.8 to 0.4.1 it's not working. 

@blaueQuelle Could you have a look on it.

Not working:

![2020-11-26 19_05_31](https://user-images.githubusercontent.com/59877407/100382243-310b3380-301b-11eb-8f57-a9d861deebf6.jpg)

Working (same code in init-matomo.js):

![2020-11-26 19_04_42](https://user-images.githubusercontent.com/59877407/100382257-39fc0500-301b-11eb-9d68-63db579c3a31.jpg)

![2020-11-26 19_05_09](https://user-images.githubusercontent.com/59877407/100382286-4a13e480-301b-11eb-95c4-47b0141fdf32.jpg)

**Comment by webworkerJoshua** [comment]
Hi @vieregg-jfc
I will have a look into this tomorrow morning and will let you know.

**Comment by vieregg-jfc** [comment]
Hey @blaueQuelle  👍 

Thank you - no need for hurry!

**Comment by webworkerJoshua** [comment]
Hey @vieregg-jfc,
I found the bug: An existing or cloned script-node will not re-run, as there already is an "already started" flag: [https://html.spec.whatwg.org/multipage/scripting.html#script-processing-model](https://html.spec.whatwg.org/multipage/scripting.html#script-processing-model)

> A script element has a flag indicating whether or not it has been "already started". Initially, script elements must have this flag unset (script blocks, when created, are not "already started"). The cloning steps for script elements must set the "already started" flag on the copy if it is set on the element being cloned.
Starting in 0.4.2 script tags will be created as new elements to trigger an execution. Thanks for noticing!

**Comment by vieregg-jfc** [comment]
@blaueQuelle Thank you for fixing this bug so quickly!
