### ISSUE TITLE
minification problems

### ISSUE THREAD

**Issue by tbba** [blaueQuelle/privacywire#13]
Hi,
the minification caused problems here, if there are comments // in it.

FIREFOX: SyntaxError: missing } after function body

Probably because the code is in one line and everything after the first // becomes a comment?

**Comment by webworkerJoshua** [comment]
In which version of PrivacyWire does this happen? I couldn't reproduce this behaviour.

**Comment by tbba** [comment]
Hi, since the feature is now gone after the latest PrivacyWire update, this problem is gone too and I think I can close this.
(I think that this is maybe an ProCache issue, but I never use esoteric minification settings there so I did not stumble upon that very specific issue before.)
Kind regards..
