### ISSUE TITLE
JS Error in IE11

### ISSUE THREAD

**Issue by webaff** [blaueQuelle/privacywire#15]
> PrivacyWire_legacy.js (1,10449)
> Object doesn't support property or method 'from'

IE11 does't like this:
`Array.from(this.elements.consentWindows)`

I assume that this JS error is the reason that PrivacyWire 1.0.4 does not run on IE11 in my ProcessWire 3.0.165 installation.
Has anyone successfully running version 1.04 in IE11?

**Comment by webworkerJoshua** [comment]
I will take a deeper look into this on Friday and test the Fix. After that I'll push the version number.

Thanks for noticing!

**Comment by vieregg-jfc** [comment]
Thank you!

**Comment by webworkerJoshua** [comment]
I just added the IE11 Polyfill for Array.from to the current version and tested via BrowserStack in Win 10 IE11 (I don't have any windows computer around anymore :D )
Looks like it's working now in IE11.

**Comment by webaff** [comment]
I confirm that 1.0.6 is working on IE11 without error.

However, there are two small inconveniences. The consent manager banner does not disappear after saving. And Youtube iframes do not load automatically after consent is given.

I don't think IE11 users need to have a perfect experience.
I am very happy with 1.0.6! Thank you very much.
