### ISSUE TITLE
initiatePrivacyWire called multiple times with FieldtypePageTable

### ISSUE THREAD

**Issue by bi11n3r** [blaueQuelle/privacywire#17]
Hello! Thanks for sharing this very useful module! 
I bumped into an issue when using the module on a site with PageTable fields.

The hooks on Page:render in ready() are called for every instance of a PageTable entry. As a result, the PrivacyWire scripts and templates are rendered multiple times.

<img width="837" alt="Bildschirmfoto 2021-09-23 um 15 11 33" src="https://user-images.githubusercontent.com/31960287/134513092-f7c2179b-f44f-488c-973c-4bb81291c3bd.png">

**Comment by webworkerJoshua** [comment]
Thanks for noticing!
What output method are you using to display the FieldtypePageTable Pages?

**Comment by bi11n3r** [comment]
I use FieldtypePageTable for content elements (sections). A page has a field of type FieldTypePageTable (sections), and when iterating over the section entries the section's render function is called. And since the section itself is a page, the Page:render hook in the module fires.

```
<?php foreach($page->sections as $section) echo $section->render(); ?>
```

**Comment by webworkerJoshua** [comment]
I found the solution to solve this buggy behaviour:
Instead of hooking into to general `Page::render` (which gets called on every render() instance, PrivacyWire now uses the `wire('page')->addHookAfter('render')` method to get called only once.

Thanks for noticing this bug!
