### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by matjazpotocnik** [blaueQuelle/privacywire#2]
https://github.com/blaueQuelle/privacywire/blob/cf4dfbe347c677f2ae596241e4178b9b439b7a9e/PrivacyWireBanner.php#L126

`priavywire-body`

**Comment by webworkerJoshua** [comment]
Thanks! Corrected in https://github.com/blaueQuelle/privacywire/commit/f7ef5075e202e7fc05304372e9da179e949fc792
