### ISSUE TITLE
Window reload

### ISSUE THREAD

**Issue by MateThemes** [blaueQuelle/privacywire#29]
Hey there,

first thank you for that great module. 

I have one question. For example if an iframe is loaded and the visitor is given the consent. Everything works fine. But what if the user decide to change the settings and want to block the iframes and changes the preferences. The visitor loads the settings and change the preferences but nothing changes. It needs a window reload and then the setting is fine. 

How is it possible to reload the window if the preferences are ajusted?

Thank you

**Comment by teppokoivula** [comment]
If you check module settings, there is an option to trigger custom JavaScript function:

> If you want to trigger a custom js function after saving the cookie banner, insert the name of the function here

You can use this to trigger any special behaviour that your site requires.

**Comment by MateThemes** [comment]
Thank you for that advice
