### ISSUE TITLE
Error Message @ PW 3.0.98 - InpuptfieldText::showIf does not exist or is not callable in this context

### ISSUE THREAD

**Issue by vieregg-jfc** [blaueQuelle/privacywire#3]
After installing and activating the module on PW 3.0.98, the setting page of the module displays an error:

![2020-06-03 08_59_33](https://user-images.githubusercontent.com/59877407/83606147-686fba80-a579-11ea-9925-edfc3869b042.jpg)

After updating PW to 3.0.148 everything is working fine.

**Comment by webworkerJoshua** [comment]
Thanks for the feedback. I just updated the required ProcessWire Core Version to [3.0.110](https://processwire.com/api/ref/inputfield/#api-showIf)
